### ISSUE TITLE
`neonctl branches get` fails for numerical branch names

### ISSUE THREAD

**Issue by maxpetretta** [neondatabase/neonctl#143]
## Steps to reproduce
- Install `neonctl` package globally
- Create branch with a numerical name, I.e. "123"
- Run `neonctl branches get 123`

## Expected result
- Branch output, in either ASCII or JSON format

## Actual result
- Throws error `ERROR: branch.startsWith is not a function`

## Environment
macOS v14.1.2, pnpm v8.6.9, neonctl v1.25.1

## Logs, links
![CleanShot 2024-01-02 at 17 52 09@2x](https://github.com/neondatabase/neonctl/assets/19291506/6ed42da0-3b1e-4e6b-98f6-ff6d292018b1)

Also discovered the version command only prints `unknown` in the course of writing this issue

**Comment by duskpoet** [comment]
Thanks for filing this! I think you can expect a fix within an hour or two.
