### ISSUE TITLE
Automate the update process for Homebrew with each release

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/neonctl#157]
So that we do not forget, we should automate the process for updating Homebrew with each new release of the Neon CLI.

Making a new version updated in homebrew requires creating a PR in the homebrew-core repo. For example:

**[#160317 neonctl 1.26.0](https://github.com/Homebrew/homebrew-core/pull/160317)**

**Comment by duskpoet** [comment]
The release in homebrew happens with a really not so big lag, should we bother? @danieltprice

**Comment by bayandin** [comment]
`neonctl` has been added to Homebrew's autobump list in https://github.com/Homebrew/homebrew-core/pull/163195, which means a PR with `neonctl` update will be created in the homebrew-core repo within 3 hours (at max). The time to get this PR approved and merged depends on the load of Homebrew maintainers (i.e. we can do nothing about it).

So, the question is, do we want to add automation to create PR to shave up to 3 hours max, or are we okay with the current situation (and then we can close this issue)?

**Comment by duskpoet** [comment]
I am cool with that, @danieltprice ?

**Comment by danieltprice** [comment]
A few hours seems very reasonable to me. Thank you @bayandin !
