### ISSUE TITLE
Inconsistent command behavior

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/neonctl#161]
If there is only a single project, a branches list command can run without specifying --project-id. 
If there is only a single project, an ip-allow list command will not run without --project-id

 neon branches list
┌─────────────────────────┬──────┬─────────┬──────────────────────┬──────────────────────┐
│ Id                      │ Name │ Primary │ Created At           │ Updated At           │
├─────────────────────────┼──────┼─────────┼──────────────────────┼──────────────────────┤
│ br-autumn-rain-92943621 │ main │ true    │ 2024-01-19T09:59:33Z │ 2024-01-19T13:06:38Z │
└─────────────────────────┴──────┴─────────┴──────────────────────┴──────────────────────┘
neon ip-allow list
ERROR: projects not found

**Comment by Shridhad** [comment]
@duskpoet I was talking about this issue in CLI. the `neonctl branch list` command works without `--project-id` option, when there is only one project under the user account, however `neonctl ip-allow list` always needs `--project-id`.

**Comment by duskpoet** [comment]
yep, we discussed, that this is a bug
