### ISSUE TITLE
Return a different exit code when `branch create` fails if the branch already exists

### ISSUE THREAD

**Issue by rberrelleza** [neondatabase/neonctl#167]
I'm starting to use neonctl as part of my CI pipeline. I want to be able to tell when the database branch creation failed because it already exists vs other reasons. 

## Steps to reproduce
```
neonctl branches create --name dev/my-branch #success!
neonctl branches create --name dev/my-branch #fails as expected
```

## Expected result
I'd like to have a separate exit code for 'branch already exists' so I can automate retries when needed without parsing the output (Im'using neon in preview environment kind of scenarios)

## Actual result
The command fails with exit code 1 regardless of the reason

## Environment
Linux

## Logs, links
-

**Comment by duskpoet** [comment]
Hey! Thanks for filing this. Do you have any similar practices in mind for other CLIs?

**Comment by duskpoet** [comment]
Ok, closing for now
