### ISSUE TITLE
Add a full tree-like hierarchical output of projects list and braches list command

### ISSUE THREAD

**Issue by duskpoet** [neondatabase/neonctl#194]
our users are asking for the CLI to be able to produce a listing without box borders so it can be fed into other tools. Right now the box borders (which look great) get in the way of that. Perhaps --noborder?

when comparing the json or yaml, they say yaml would work like a charm

**Comment by mrl5** [comment]
how about sneak-peaking at AWS CLI syntax -> https://docs.aws.amazon.com/cli/v1/userguide/cli-usage-output-format.html

so this could go like this:
```console
neonctl projects list --output json
```
