### ISSUE TITLE
no neonctl binary for 1.29.1 release

### ISSUE THREAD

**Issue by chenrui333** [neondatabase/neonctl#210]
👋 looks like there is packaging issue for 1.29.1 release, ie the binary file is missing? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/169553

**Comment by duskpoet** [comment]
There was a broken pipeline, the current release v1.29.3 is fine

**Comment by chenrui333** [comment]
let me re-try my pr, thanks! :)

**Comment by chenrui333** [comment]
@duskpoet did you publish a new artifact? I am still seeing the old artifact.

**Comment by chenrui333** [comment]
1.29.3 works for me now, closing this issue. Thanks for the quick turnaround!

**Comment by duskpoet** [comment]
Thanks for noticing!
