### ISSUE TITLE
`connection-string` output getting overwritten

### ISSUE THREAD

**Issue by mattrossman** [neondatabase/neonctl#70]
## Steps to reproduce

Add neonctl as a project dependency with yarn: `yarn add -D neonctl`

Setup with `yarn neonctl auth`

Run the connection-string command using the local neonctl with your choice of arguments:

```yarn neonctl connection-string [...arguments]```

## Expected result

The connection string should be visible in the CLI output.

## Actual result

The connection string appears briefly, but is overwritten by yarn's `✨  Done in 1.55s.` message.

## Environment

MacOS, yarn 1.22.19, neonctl 0.1.0

## Suggested fix

I think it just needs to include a `\n` after writing to stdout:

https://github.com/neondatabase/neonctl/blob/f21c292342eb74e8671eeb0e42169912ffd4ba49/src/commands/connection_string.ts#L135

**Comment by duskpoet** [comment]
I think whatever yarn writes is going to stderr, not stdout. Anyway you can silence that output by providing "-s" option, like this: `yarn -s neonctl cs`
