### ISSUE TITLE
Connection string prevents passing branch-id with 8 digit suffix

### ISSUE THREAD

**Issue by mmachatschek** [neondatabase/neonctl#84]
## Steps to reproduce

Try to generate a connection string by providing a branch-id instead of the branch

## Expected result

The CLI tool should allow both branch name and branch id to be passed into the connection-string

## Actual result

CLI shows:

```
ERROR: Branch br-xyz-zyx-12345678 not found.
```

## Issue

The regex only expects branch ids to have a 6 digit suffix, but newly created ones have 8 digits

https://github.com/neondatabase/neonctl/blob/8b4ab0576875599348654a73c654e71be49505fe/src/utils/formats.ts#L1C1-L1C45

**Comment by mmachatschek** [comment]
@duskpoet I think this is a serious issue. Our GH action started to break out of nowhere

**Comment by duskpoet** [comment]
Thanks for reporting! Expect fix to arrive within 2 hours

**Comment by mmachatschek** [comment]
@duskpoet already submitted a fix at #85

**Comment by mmachatschek** [comment]
@duskpoet added fixes here too:

- https://github.com/neondatabase/create-branch-action/pull/17
- https://github.com/neondatabase/delete-branch-action/pull/9
